[package]
name = "day-1-sonar-sweep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day-1-part-1"
path = "bin/part-one.rs"


[[bin]]
name = "day-1-part-2"
path = "bin/part-two.rs"